spring.application.name=gym-backend

spring.datasource.url=jdbc:mysql://localhost:3306/gym
spring.datasource.username=temp
spring.datasource.password=temporary
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=144740755127-1416kcu4fi7b3qlq5sst3tnj71tpo925.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

jwt.secret.key=hh83bub4u8g3u3gf833ufbne48373bu3u3fb8478kkwxmkdg33
